// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJaPVqchLOp_dSEUkb0k6ZFrsK8XfR1qk',
    appId: '1:577932282164:web:d0f07d0fc6103c76af7d61',
    messagingSenderId: '577932282164',
    projectId: 'safarsuraksha',
    authDomain: 'safarsuraksha.firebaseapp.com',
    storageBucket: 'safarsuraksha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Z9mg4sedmDRfPKPQesq4I5owkfSLnF4',
    appId: '1:577932282164:android:4fa0e65f0c54e522af7d61',
    messagingSenderId: '577932282164',
    projectId: 'safarsuraksha',
    storageBucket: 'safarsuraksha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_oIMLblNVZBuQeIXqX5jz3cLobZsdzU',
    appId: '1:577932282164:ios:eb19b7bbf434e3c4af7d61',
    messagingSenderId: '577932282164',
    projectId: 'safarsuraksha',
    storageBucket: 'safarsuraksha.firebasestorage.app',
    iosBundleId: 'com.example.sihpixeltroops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh_oIMLblNVZBuQeIXqX5jz3cLobZsdzU',
    appId: '1:577932282164:ios:6370b58cc985538caf7d61',
    messagingSenderId: '577932282164',
    projectId: 'safarsuraksha',
    storageBucket: 'safarsuraksha.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJaPVqchLOp_dSEUkb0k6ZFrsK8XfR1qk',
    appId: '1:577932282164:web:d8887785eee274e9af7d61',
    messagingSenderId: '577932282164',
    projectId: 'safarsuraksha',
    authDomain: 'safarsuraksha.firebaseapp.com',
    storageBucket: 'safarsuraksha.firebasestorage.app',
  );
}
